version: '2.0'
services:
  ovif-capture-rotate:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.txt
    container_name: ovif-capture-rotate
    image: maskawanian/ovif-capture-rotate:latest
    restart: always
    volumes:
      - ./data-CCTV:/CCTV
      - ./config.ini:/app/config.ini